{application,exrm,
             [{registered,[]},
              {description,"Exrm, or Elixir Release Manager, provides mix tasks for building, \nupgrading, and controlling release packages for your application.\n"},
              {vsn,"0.19.2"},
              {modules,['Elixir.Mix.Tasks.Release',
                        'Elixir.Mix.Tasks.Release.Clean',
                        'Elixir.Mix.Tasks.Release.Plugins',
                        'Elixir.ReleaseManager.Appups',
                        'Elixir.ReleaseManager.Config',
                        'Elixir.ReleaseManager.Plugin',
                        'Elixir.ReleaseManager.Plugin.Appups',
                        'Elixir.ReleaseManager.Plugin.Conform',
                        'Elixir.ReleaseManager.Plugin.Consolidation',
                        'Elixir.ReleaseManager.Utils']},
              {applications,[kernel,stdlib,elixir]}]}.