{application,conform,
             [{registered,[]},
              {description,"Easy release configuration for Elixir apps."},
              {applications,[kernel,stdlib,elixir]},
              {vsn,"0.16.0"},
              {modules,['Elixir.Conform','Elixir.Conform.Config',
                        'Elixir.Conform.Options','Elixir.Conform.Parse',
                        'Elixir.Conform.Schema',
                        'Elixir.Conform.Schema.SchemaError',
                        'Elixir.Conform.Translate',
                        'Elixir.Conform.Translate.TranslateError',
                        'Elixir.Conform.Type','Elixir.Conform.Types.Enum',
                        'Elixir.Conform.Utils','Elixir.Conform.Utils.Code',
                        'Elixir.Mix.Tasks.Conform.Archive',
                        'Elixir.Mix.Tasks.Conform.Configure',
                        'Elixir.Mix.Tasks.Conform.Effective',
                        'Elixir.Mix.Tasks.Conform.New',
                        'Elixir.Mix.Tasks.Conform.Release',conf_parse]}]}.